name: content_resolver
description: A plugin that help app to call ContentResolver on Android.
version: 0.3.5
repository: https://github.com/espresso3389/flutter_content_resolver

environment:
  sdk: ^3.0.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: jp.espresso3389.content_resolver
        pluginClass: ContentResolverPlugin

